export const ERROR_CODES = {
  UNKNOWN: 'UNKNOWN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',

  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_USED: 'TOKEN_USED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  RATE_LIMITED: 'RATE_LIMITED',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
